USE UsaCarriers_DW
GO

SELECT *, 
    'Y'+CAST(YEAR AS VARCHAR) AS NEWYEAR,
	'Q'+CAST(QUARTER AS VARCHAR) AS NEWQUARTER,
	'M'+CAST(MONTH AS VARCHAR) AS NEWMONTH
FROM dbo.DimFlightdate;

SELECT df.YEAR,df.QUARTER,df.MONTH,
       ds.UNIQUE_CARRIER_NAME,
	   ac.AIRCRAFT_TYPE,
	   apo.STATE_NM,apo.CITY_NAME,apo.IATACODE,
	   apd.STATE_NM,apd.CITY_NAME,apd.IATACODE,
	   fs.PAYLOAD_RATE,
	   fs.PASSENGER_RATE,
	   fs.FLIGHT_EFFICIENCY
FROM dbo.FactSummary fs
JOIN dbo.DimAircraft ac ON fs.AIRCRAFT_KEY = ac.AIRCRAFT_KEY
JOIN dbo.DimAirport apo ON fs.ORIGIN_AIRPORT_KEY = apo.AIRPORT_KEY
JOIN dbo.DimAirport apd ON fs.DEST_AIRPORT_KEY = apd.AIRPORT_KEY
JOIN dbo.DimCarrier ds ON fs.CARRIER_KEY = ds.CARRIER_KEY
JOIN dbo.DimFlightdate df ON fs.FLIGHTDATE_KEY = df.FLIGHTDATE_KEY


SELECT * FROM dbo.DimAirport;
SELECT SUM(PASSENGERS) AS TOTALPASSENGERS
FROM dbo.FactSummary;

SELECT SUM(MAIL) AS TOTALMAILS
FROM dbo.FactSummary;

SELECT COUNT(*) AS TOTALCOUNTS
FROM dbo.FactSummary;

SELECT PASSENGER_RATE
FROM dbo.FactSummary

--Get Passengers, Origin City Wise
SELECT da.CITY_NAME,SUM(fs.PASSENGERS) AS TOTALPASSENGERS
FROM dbo.FactSummary AS fs 
JOIN dbo.DimAirport AS da
ON fs.ORIGIN_AIRPORT_KEY = da.AIRPORT_KEY
GROUP BY da.CITY_NAME

--Get Flight Effiency, Origin Airport Wise, only for Quarter 4
SELECT da.IATACODE,SUM(fs.FLIGHT_EFFICIENCY) AS FIGHTEFFICIENCY
FROM dbo.FactSummary AS fs 
JOIN dbo.DimAirport AS da
ON fs.ORIGIN_AIRPORT_KEY = da.AIRPORT_KEY
JOIN dbo.DimFlightdate AS df
ON fs.FLIGHTDATE_KEY = df.FLIGHTDATE_KEY
WHERE df.QUARTER=4
GROUP BY da.IATACODE


